/**************************************************************************
Project ID: EMS3103
Project Name: Apollo Digital And ASI Development
Code Developed by: Makarand Deshmukh
Date modified: 28-05-2014

RS ID:
DLD ID:
Function Name:
Function Description:
**************************************************************************/

#define SIZEOF_LONG	4
#define EE_ADDR_FIRST_PWR_UP		0x00
#define EE_ADDR_OFFSET 				0x04

#define EE_ADDR_ENERGIZED			(EE_ADDR_OFFSET)							// Energised position
#define EE_ADDR_DE_ENERGIZED		(EE_ADDR_ENERGIZED + SIZEOF_LONG)			// De energised position
#define EE_ADDR_LSL_VALUE			(EE_ADDR_DE_ENERGIZED + SIZEOF_LONG)		// Lower seat lift
#define EE_ADDR_USL_VALUE			(EE_ADDR_LSL_VALUE + SIZEOF_LONG)			// Upper seat lift
#define EE_ADDR_ENG_TOL_HIGH		(EE_ADDR_USL_VALUE + SIZEOF_LONG)			// Tolerance band high energised
#define EE_ADDR_ENG_TOL_LOW			(EE_ADDR_ENG_TOL_HIGH + SIZEOF_LONG)		// Tolerance band low energised
#define EE_ADDR_DNG_TOL_HIGH		(EE_ADDR_ENG_TOL_LOW + SIZEOF_LONG)			// Tolerance band high de energised
#define EE_ADDR_DNG_TOL_LOW			(EE_ADDR_DNG_TOL_HIGH + SIZEOF_LONG)		// Tolerance band low de energised
#define EE_ADDR_SL_TOL_HIGH			(EE_ADDR_DNG_TOL_LOW + SIZEOF_LONG)			// Tolerance band high seat lift
#define EE_ADDR_SL_TOL_LOW			(EE_ADDR_SL_TOL_HIGH + SIZEOF_LONG)			// Tolerance band low seat lift
#define EE_ADDR_VALVE_TYPE			(EE_ADDR_SL_TOL_LOW + SIZEOF_LONG)			// Valve type
#define EE_ADDR_OPERATION_TIME		(EE_ADDR_VALVE_TYPE + SIZEOF_LONG)			// Total time of operation
#define EE_ADDR_NO_OF_STROKES		(EE_ADDR_OPERATION_TIME + SIZEOF_LONG)		// Total no of strokes
#define EE_ADDR_DATE_FW				(EE_ADDR_NO_OF_STROKES + SIZEOF_LONG)		// Firmware flash date
#define EE_ADDR_FW_REVISION			(EE_ADDR_DATE_FW + SIZEOF_LONG)				// Firmware revision
#define EE_ADDR_PCB_REVISION		(EE_ADDR_FW_REVISION + SIZEOF_LONG)			// PCB revision
#define EE_ADDR_MAX_TEMP			(EE_ADDR_PCB_REVISION + SIZEOF_LONG)		// Maximum Temperature
#define EE_ADDR_EXTSEN_ON			(EE_ADDR_MAX_TEMP + SIZEOF_LONG)			// External sensor activated
#define EE_ADDR_EXTSEN_OFF			(EE_ADDR_EXTSEN_ON + SIZEOF_LONG)			// External sensor de activated
#define EE_ADDR_TOTSV1_ACT			(EE_ADDR_EXTSEN_OFF + SIZEOF_LONG)			// Total solenoid 1 activations
#define EE_ADDR_TOTSV2_ACT			(EE_ADDR_TOTSV1_ACT + SIZEOF_LONG)			// Total solenoid 2 activations
#define EE_ADDR_TOTSV3_ACT			(EE_ADDR_TOTSV2_ACT + SIZEOF_LONG)			// Total solenoid 3 activations
#define EE_ADDR_ERROR_TIME1			(EE_ADDR_ERROR_NO1 + SIZEOF_LONG)
#define EE_ADDR_ERROR_DURA1			(EE_ADDR_ERROR_TIME1 + SIZEOF_LONG)
#define EE_ADDR_ERROR_CODE1			(EE_ADDR_ERROR_DURA1 + SIZEOF_LONG)
#define EE_ADDR_ERROR_NO2			(EE_ADDR_ERROR_CODE1 + SIZEOF_LONG)
#define EE_ADDR_ERROR_TIME2			(EE_ADDR_ERROR_NO2 + SIZEOF_LONG)
#define EE_ADDR_ERROR_DURA2			(EE_ADDR_ERROR_TIME2 + SIZEOF_LONG)
#define EE_ADDR_ERROR_CODE2			(EE_ADDR_ERROR_DURA2 + SIZEOF_LONG)
#define EE_ADDR_ERROR_NO3			(EE_ADDR_ERROR_CODE2 + SIZEOF_LONG)
#define EE_ADDR_ERROR_TIME3			(EE_ADDR_ERROR_NO3 + SIZEOF_LONG)
#define EE_ADDR_ERROR_DURA3			(EE_ADDR_ERROR_TIME3 + SIZEOF_LONG)
#define EE_ADDR_ERROR_CODE3			(EE_ADDR_ERROR_DURA3 + SIZEOF_LONG)
#define EE_ADDR_ERROR_NO4			(EE_ADDR_ERROR_CODE3 + SIZEOF_LONG)
#define EE_ADDR_ERROR_TIME4			(EE_ADDR_ERROR_NO4 + SIZEOF_LONG)
#define EE_ADDR_ERROR_DURA4			(EE_ADDR_ERROR_TIME4 + SIZEOF_LONG)
#define EE_ADDR_ERROR_CODE4			(EE_ADDR_ERROR_DURA4 + SIZEOF_LONG)
#define EE_ADDR_ERROR_NO5			(EE_ADDR_ERROR_CODE4 + SIZEOF_LONG)
#define EE_ADDR_ERROR_TIME5			(EE_ADDR_ERROR_NO5 + SIZEOF_LONG)
#define EE_ADDR_ERROR_DURA5			(EE_ADDR_ERROR_TIME5 + SIZEOF_LONG)
#define EE_ADDR_ERROR_CODE5			(EE_ADDR_ERROR_DURA5 + SIZEOF_LONG)
#define EE_ADDR_ERROR_NO6			(EE_ADDR_ERROR_CODE5 + SIZEOF_LONG)
#define EE_ADDR_ERROR_TIME6			(EE_ADDR_ERROR_NO6 + SIZEOF_LONG)
#define EE_ADDR_ERROR_DURA6			(EE_ADDR_ERROR_TIME6 + SIZEOF_LONG)
#define EE_ADDR_ERROR_CODE6			(EE_ADDR_ERROR_DURA6 + SIZEOF_LONG)
#define EE_ADDR_ERROR_NO7			(EE_ADDR_ERROR_CODE6 + SIZEOF_LONG)
#define EE_ADDR_ERROR_TIME7			(EE_ADDR_ERROR_NO7 + SIZEOF_LONG)
#define EE_ADDR_ERROR_DURA7			(EE_ADDR_ERROR_TIME7 + SIZEOF_LONG)
#define EE_ADDR_ERROR_CODE7			(EE_ADDR_ERROR_DURA7 + SIZEOF_LONG)
#define EE_ADDR_ERROR_NO8			(EE_ADDR_ERROR_CODE7 + SIZEOF_LONG)
#define EE_ADDR_ERROR_TIME8			(EE_ADDR_ERROR_NO8 + SIZEOF_LONG)
#define EE_ADDR_ERROR_DURA8			(EE_ADDR_ERROR_TIME8 + SIZEOF_LONG)
#define EE_ADDR_ERROR_CODE8			(EE_ADDR_ERROR_DURA8 + SIZEOF_LONG)
#define EE_ADDR_ERROR_NO9			(EE_ADDR_ERROR_CODE8 + SIZEOF_LONG)
#define EE_ADDR_ERROR_TIME9			(EE_ADDR_ERROR_NO9 + SIZEOF_LONG)
#define EE_ADDR_ERROR_DURA9			(EE_ADDR_ERROR_TIME9 + SIZEOF_LONG)
#define EE_ADDR_ERROR_CODE9			(EE_ADDR_ERROR_DURA9 + SIZEOF_LONG)
#define EE_ADDR_ERROR_NO10			(EE_ADDR_ERROR_CODE9 + SIZEOF_LONG)
#define EE_ADDR_ERROR_TIME10		(EE_ADDR_ERROR_NO10 + SIZEOF_LONG)
#define EE_ADDR_ERROR_DURA10		(EE_ADDR_ERROR_TIME10 + SIZEOF_LONG)
#define EE_ADDR_ERROR_CODE10		(EE_ADDR_ERROR_DURA10 + SIZEOF_LONG)
#define EE_ADDR_SOLENOID_ONE		(EE_ADDR_ERROR_CODE10 + SIZEOF_LONG)
#define EE_ADDR_SOLENOID_TWO		(EE_ADDR_SOLENOID_ONE + SIZEOF_LONG)
#define EE_ADDR_SOLENOID_THREE		(EE_ADDR_SOLENOID_TWO + SIZEOF_LONG)
#define EE_ADDR_EXTSEN_DEN			(EE_ADDR_SOLENOID_THREE + SIZEOF_LONG)
#define EE_ADDR_EXTSEN_EN			(EE_ADDR_EXTSEN_DEN + SIZEOF_LONG)
#define EE_ADDR_EXTSEN_LSL			(EE_ADDR_EXTSEN_EN + SIZEOF_LONG)
#define EE_ADDR_CALIBRATION			(EE_ADDR_EXTSEN_LSL + SIZEOF_LONG)

// EEPROM Functions Used
void EEPROMWriteOperation(U32 *, U32 , U32);
